apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: eureka-server
spec:
  selector:
    matchLabels:
      app: eureka-server
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: masudbappy/eureka-service:eureka # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761 # The port that the container is running on in the cluster